import type { Metadata } from "next";
import { LegalMeta, LegalPageShell } from "../_components/legal-page-shell";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Terms of Service for REOS by Referral Partners, LLC governing access to and use of the Service.",
};

export default function TermsOfServicePage() {
  return (
    <LegalPageShell title="Terms of Service">
      <LegalMeta effectiveDate="September 2, 2026" lastUpdated="September 2, 2026" />

      <p>
        These Terms of Service (&quot;Terms&quot;) govern your access to and use of{" "}
        <strong>REOS</strong> (&quot;REOS,&quot; the &quot;Service,&quot; or the
        &quot;App&quot;) provided by <strong>Referral Partners, LLC</strong>{" "}
        (&quot;Referral Partners,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;).
      </p>

      <p>
        By creating an account or using REOS, you agree to these Terms. If you do not agree
        to these Terms, you may not use the Service.
      </p>

      <h2>1. The REOS Service</h2>
      <p>
        REOS is a software platform designed to help real estate professionals manage
        relationships, leads, opportunities, communications, tasks, calendars, workflows,
        and related business activities.
      </p>
      <p>Features may change over time as we improve and expand the Service.</p>
      <p>
        We may add, modify, suspend, or discontinue features or functionality at any time.
        We will make reasonable efforts to provide notice of material changes that
        negatively affect your use of the Service.
      </p>

      <h2>2. Your Account</h2>
      <p>You must provide accurate and complete information when creating an account.</p>
      <p>You are responsible for:</p>
      <ul>
        <li>Maintaining the confidentiality of your account credentials</li>
        <li>Maintaining accurate account information</li>
        <li>All activity occurring under your account</li>
        <li>Notifying us promptly of unauthorized access or use</li>
      </ul>
      <p>
        You may not share your account credentials with another person or allow unauthorized
        individuals to access your account.
      </p>

      <h2>3. Your Data</h2>
      <p>
        You retain ownership of the information and content that you submit to REOS
        (&quot;Your Data&quot;).
      </p>
      <p>
        You grant us a limited, non-exclusive right to host, store, process, transmit, and
        otherwise use Your Data solely as necessary to provide, maintain, secure, and
        improve the Service and as otherwise permitted by these Terms or our Privacy Policy.
      </p>
      <p>
        You are responsible for Your Data and for ensuring that your collection, use, and
        processing of that data complies with applicable laws and your agreements with third
        parties.
      </p>

      <h2>4. Communications and Connected Accounts</h2>
      <p>
        REOS may allow you to connect external services, including email, calendar,
        messaging, and social media platforms.
      </p>
      <p>
        By connecting an external service, you authorize REOS to access and process
        information from that service as necessary to provide the functionality you have
        enabled.
      </p>
      <p>
        You are responsible for ensuring that your use of those integrations complies with
        the applicable third party&apos;s terms, policies, and requirements.
      </p>
      <p>
        You are also responsible for the content of communications you send through REOS and
        for ensuring that you have the appropriate rights and permissions to contact
        recipients.
      </p>

      <h2>5. AI and Automation Features</h2>
      <p>
        REOS may provide AI-powered features, automated workflows, recommendations,
        generated content, or other automated functionality.
      </p>
      <p>
        AI-generated or automated output may contain errors or omissions and should not be
        treated as guaranteed accurate.
      </p>
      <p>
        You are responsible for reviewing and approving content, recommendations, messages,
        or actions generated by REOS before relying on them when human review is
        appropriate.
      </p>
      <p>
        You remain responsible for decisions made using information or output provided by
        the Service.
      </p>

      <h2>6. Acceptable Use</h2>
      <p>You agree not to use REOS to:</p>
      <ul>
        <li>Violate any applicable law or regulation</li>
        <li>Infringe the rights of another person or organization</li>
        <li>Access accounts or information without authorization</li>
        <li>
          Send unlawful, fraudulent, deceptive, abusive, or malicious communications
        </li>
        <li>Distribute malware or other harmful code</li>
        <li>Interfere with the operation or security of the Service</li>
        <li>Attempt to gain unauthorized access to the Service or its systems</li>
        <li>Circumvent usage limits, security controls, or access restrictions</li>
        <li>
          Reverse engineer or attempt to extract source code from the Service except where
          expressly permitted by law
        </li>
        <li>Use the Service to facilitate spam, harassment, or unlawful solicitation</li>
        <li>Upload information that you do not have the right to process</li>
      </ul>
      <p>
        We may suspend or terminate access when we reasonably believe the Service is being
        used in violation of these Terms or in a manner that creates risk to REOS, its
        users, or others.
      </p>

      <h2>7. Real Estate and Professional Responsibility</h2>
      <p>
        REOS is a software and productivity platform. It does not provide legal, financial,
        tax, brokerage, real estate, or other professional advice.
      </p>
      <p>
        REOS does not replace the professional judgment, supervision, licensing obligations,
        or responsibilities of real estate professionals.
      </p>
      <p>
        You are responsible for ensuring that your use of REOS complies with applicable
        federal, state, and local laws, regulations, licensing requirements, brokerage
        policies, and professional obligations.
      </p>

      <h2>8. Third-Party Services</h2>
      <p>REOS may depend on or integrate with third-party products and services.</p>
      <p>Third-party services are controlled by their respective providers, not REOS.</p>
      <p>
        We are not responsible for the availability, functionality, security, policies, or
        practices of third-party services.
      </p>
      <p>Changes made by third-party providers may affect REOS functionality.</p>

      <h2>9. Subscriptions and Payments</h2>
      <p>Certain REOS features may require a paid subscription.</p>
      <p>
        If you purchase a subscription, you agree to pay the applicable fees and any
        applicable taxes.
      </p>
      <p>
        Subscriptions may automatically renew unless canceled in accordance with the
        applicable subscription terms.
      </p>
      <p>
        We may change subscription pricing from time to time. Where required by law, we will
        provide advance notice of material pricing changes.
      </p>
      <p>
        Unless otherwise stated, fees paid for the Service are non-refundable except where
        required by law or expressly provided by us.
      </p>

      <h2>10. Intellectual Property</h2>
      <p>
        REOS and its software, interfaces, designs, branding, features, documentation, and
        underlying technology are owned by or licensed to Referral Partners, LLC and are
        protected by applicable intellectual property laws.
      </p>
      <p>
        Except for the rights expressly granted under these Terms, Referral Partners, LLC
        retains all rights, title, and interest in and to the Service.
      </p>
      <p>
        You may not copy, modify, distribute, sell, lease, sublicense, or create derivative
        works of the Service except as expressly permitted by these Terms or applicable law.
      </p>

      <h2>11. Feedback</h2>
      <p>
        If you provide suggestions, ideas, recommendations, or other feedback about REOS,
        you grant us the right to use that feedback without restriction or compensation to
        you.
      </p>
      <p>We will not use your confidential business information as feedback.</p>

      <h2>12. Availability and Changes</h2>
      <p>
        We strive to keep REOS available and reliable, but we do not guarantee that the
        Service will always be uninterrupted, error-free, or available.
      </p>
      <p>
        The Service may occasionally be unavailable because of maintenance, updates,
        outages, third-party services, security incidents, or circumstances outside our
        reasonable control.
      </p>

      <h2>13. Disclaimer of Warranties</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, REOS IS PROVIDED &quot;AS IS&quot; AND
        &quot;AS AVAILABLE.&quot;
      </p>
      <p>
        WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF
        MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, AND THAT
        THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE.
      </p>

      <h2>14. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, REFERRAL PARTNERS, LLC AND ITS AFFILIATES,
        OFFICERS, DIRECTORS, EMPLOYEES, CONTRACTORS, AND SERVICE PROVIDERS WILL NOT BE
        LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE
        DAMAGES, OR FOR LOST PROFITS, LOST REVENUE, LOST DATA, OR BUSINESS INTERRUPTION
        ARISING FROM OR RELATED TO YOUR USE OF THE SERVICE.
      </p>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR TOTAL LIABILITY ARISING FROM OR RELATED
        TO THE SERVICE WILL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID US FOR THE
        SERVICE DURING THE TWELVE MONTHS BEFORE THE EVENT GIVING RISE TO THE CLAIM OR (B)
        $100.
      </p>
      <p>
        Some jurisdictions do not allow certain limitations of liability, so some of these
        limitations may not apply to you.
      </p>

      <h2>15. Indemnification</h2>
      <p>
        To the extent permitted by law, you agree to defend, indemnify, and hold harmless
        Referral Partners, LLC and its affiliates, officers, directors, employees, and
        agents from claims, liabilities, damages, losses, and expenses arising from:
      </p>
      <ul>
        <li>Your use or misuse of REOS</li>
        <li>Your violation of these Terms</li>
        <li>Your violation of applicable law</li>
        <li>Your violation of another person&apos;s rights</li>
        <li>Your Data or content submitted through the Service</li>
        <li>Communications or actions taken through your account</li>
      </ul>

      <h2>16. Suspension and Termination</h2>
      <p>You may stop using REOS at any time.</p>
      <p>We may suspend or terminate your access if:</p>
      <ul>
        <li>You materially violate these Terms</li>
        <li>Your account presents a security or legal risk</li>
        <li>You engage in fraudulent or abusive activity</li>
        <li>You fail to pay applicable fees</li>
        <li>We discontinue the Service</li>
      </ul>
      <p>Upon termination, your right to use REOS will end.</p>
      <p>
        Subject to applicable law and our data retention practices, we may delete or
        otherwise dispose of information associated with your account following termination.
      </p>

      <h2>17. Governing Law</h2>
      <p>
        These Terms will be governed by the laws of the <strong>State of Florida</strong>,
        without regard to conflict-of-law principles, except where applicable law requires
        otherwise.
      </p>
      <p>
        Any disputes will be handled in the courts located in Florida, unless applicable law
        requires otherwise.
      </p>

      <h2>18. Changes to These Terms</h2>
      <p>We may update these Terms from time to time.</p>
      <p>
        If we make material changes, we may provide notice through REOS, by email, or
        through another reasonable method.
      </p>
      <p>
        Your continued use of REOS after the effective date of updated Terms constitutes
        acceptance of the revised Terms, to the extent permitted by law.
      </p>

      <h2>19. General</h2>
      <p>
        These Terms constitute the agreement between you and Referral Partners, LLC regarding
        your use of REOS and supersede prior agreements concerning the Service, except where
        a separate written agreement expressly governs.
      </p>
      <p>
        If any provision is determined to be unenforceable, the remaining provisions will
        remain in effect.
      </p>
      <p>
        Our failure to enforce a provision does not waive our right to enforce it later.
      </p>
      <p>
        You may not assign your rights or obligations under these Terms without our prior
        written consent, except where permitted by law.
      </p>

      <h2>20. Contact Us</h2>
      <p>Questions regarding these Terms may be sent to:</p>
      <p>
        <strong>Referral Partners, LLC</strong>
        <br />
        <strong>Email:</strong>{" "}
        <a href="mailto:support@referralpartners.io">support@referralpartners.io</a>
      </p>
    </LegalPageShell>
  );
}
